{% set name = "fastapi" %}
{% set version = "0.96.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71232d47c2787446991c81c41c249f8a16238d52d779c0e6b43927d3773dbe3c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - starlette >=0.27.0,<0.28.0
    - pydantic >=1.6.2,!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0

test:
  imports:
    - fastapi
    - fastapi.dependencies
    - fastapi.middleware
    - fastapi.openapi
    - fastapi.security

about:
  home: https://github.com/tiangolo/fastapi
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  doc_url: https://github.com/tiangolo/fastapi
  dev_url: https://github.com/tiangolo/fastapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
